package tui

func getAllLanguages() []string {
	return []string{
		"Arabic (Saudi Arabia) - ar-SA",
		"Arabic (UAE) - ar-AE",
		"Arabic (Egypt) - ar-EG",
		"Arabic (Iraq) - ar-IQ",
		"Arabic (Jordan) - ar-JO",
		"Arabic (Kuwait) - ar-KW",
		"Arabic (Lebanon) - ar-LB",
		"Arabic (Morocco) - ar-MA",
		"Arabic (Oman) - ar-OM",
		"Arabic (Qatar) - ar-QA",
		"Arabic (Syria) - ar-SY",
		"Bengali (India) - bn-IN",
		"Bulgarian - bg-BG",
		"Burmese - my-MM",
		"Catalan - ca-ES",
		"Chinese (Cantonese) - yue-HK",
		"Chinese (Mandarin, China) - zh-CN",
		"Chinese (Mandarin, Taiwan) - zh-TW",
		"Croatian - hr-HR",
		"Czech - cs-CZ",
		"Danish - da-DK",
		"Dutch (Belgium) - nl-BE",
		"Dutch (Netherlands) - nl-NL",
		"English (Australia) - en-AU",
		"English (UK) - en-GB",
		"English (US) - en-US",
		"English (Canada) - en-CA",
		"English (India) - en-IN",
		"English (Ireland) - en-IE",
		"English (New Zealand) - en-NZ",
		"English (Philippines) - en-PH",
		"English (Singapore) - en-SG",
		"English (South Africa) - en-ZA",
		"Estonian - et-EE",
		"Filipino - fil-PH",
		"Finnish - fi-FI",
		"French (Belgium) - fr-BE",
		"French (Canada) - fr-CA",
		"French (France) - fr-FR",
		"French (Switzerland) - fr-CH",
		"Galician - gl-ES",
		"Georgian - ka-GE",
		"German (Austria) - de-AT",
		"German (Germany) - de-DE",
		"German (Switzerland) - de-CH",
		"Greek - el-GR",
		"Gujarati - gu-IN",
		"Hebrew - he-IL",
		"Hindi (India) - hi-IN",
		"Hungarian - hu-HU",
		"Icelandic - is-IS",
		"Indonesian - id-ID",
		"Italian (Italy) - it-IT",
		"Italian (Switzerland) - it-CH",
		"Japanese - ja-JP",
		"Javanese - jv-ID",
		"Kannada - kn-IN",
		"Kazakh - kk-KZ",
		"Khmer - km-KH",
		"Korean - ko-KR",
		"Lao - lo-LA",
		"Latvian - lv-LV",
		"Lithuanian - lt-LT",
		"Macedonian - mk-MK",
		"Malay (Malaysia) - ms-MY",
		"Malayalam - ml-IN",
		"Marathi - mr-IN",
		"Mongolian - mn-MN",
		"Nepali - ne-NP",
		"Norwegian (Bokmål) - nb-NO",
		"Norwegian (Nynorsk) - nn-NO",
		"Pashto - ps-AF",
		"Persian (Iran) - fa-IR",
		"Polish - pl-PL",
		"Portuguese (Brazil) - pt-BR",
		"Portuguese (Portugal) - pt-PT",
		"Punjabi (India) - pa-IN",
		"Romanian - ro-RO",
		"Russian - ru-RU",
		"Serbian - sr-RS",
		"Sinhala - si-LK",
		"Slovak - sk-SK",
		"Slovenian - sl-SI",
		"Spanish (Argentina) - es-AR",
		"Spanish (Colombia) - es-CO",
		"Spanish (Latin America) - es-419",
		"Spanish (Mexico) - es-MX",
		"Spanish (Spain) - es-ES",
		"Spanish (US) - es-US",
		"Swahili - sw-KE",
		"Swedish - sv-SE",
		"Tamil (India) - ta-IN",
		"Tamil (Malaysia) - ta-MY",
		"Tamil (Singapore) - ta-SG",
		"Telugu - te-IN",
		"Thai - th-TH",
		"Turkish - tr-TR",
		"Ukrainian - uk-UA",
		"Urdu (India) - ur-IN",
		"Urdu (Pakistan) - ur-PK",
		"Uzbek - uz-UZ",
		"Vietnamese - vi-VN",
		"Welsh - cy-GB",
		"Zulu - zu-ZA",
	}
}
